=== x-jrga/looks/colors.xsd
<xsd:schema version="1.0"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="colors">
        <xsd:annotation>
            <xsd:documentation>
                Data Exchange Document Schema For Palette Viewer Software
                Palette Viewer: Software to Create Color Palettes.
                Author: Jorge Garcia R de Alba
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="color" type="color_type" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="Uniquely_Specified_Color">
            <xsd:selector xpath="color"/>
            <xsd:field xpath="red"/>
            <xsd:field xpath="green"/>
            <xsd:field xpath="blue"/>
        </xsd:unique>
    </xsd:element>
    <!-- Color -->
    <xsd:complexType name="color_type">
        <xsd:sequence>               
            <xsd:element name="red" type="red_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="green" type="green_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="blue" type="blue_type" minOccurs="1" maxOccurs="1"/>         
        </xsd:sequence>
    </xsd:complexType>    
    <!-- Red -->
    <xsd:simpleType name="red_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Green -->
    <xsd:simpleType name="green_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Blue -->
    <xsd:simpleType name="blue_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== x-jrga/looks/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<colors xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/colors.xsd">
    <color>
        <red>255</red>
        <green>255</green>
        <blue>255</blue>
    </color>
    <color>
        <red>255</red>
        <green>204</green>
        <blue>0</blue>
    </color>
    <color>
        <red>51</red>
        <green>102</green>
        <blue>0</blue>
    </color>
    <color>
        <red>0</red>
        <green>204</green>
        <blue>255</blue>
    </color>
</colors>
